### ISSUE TITLE
font-face src-property

### ISSUE THREAD

**Issue by lifecom** [Cerdic/CSSTidy#38]
E.g. Bootstrap Glyphicons font-face.

**Before:**
```css
@font-face {
    font-family: 'Glyphicons Halflings';
    src: url('../fonts/glyphicons-halflings-regular.eot');
    src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'),
         url('../fonts/glyphicons-halflings-regular.woff') format('woff'),
         url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'),
         url('../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```
**After** (w/o minification for clarity)
```css
@font-face {
    font-family: "Glyphicons Halflings";
    src: url("") format("embedded-opentype"),
         url("../fonts/glyphicons-halflings-regular.woff") format("woff"),
         url("../fonts/glyphicons-halflings-regular.ttf") format("truetype"),
         url("") format("svg");
}
```
**The problems:**
* ~~shows only **last** src-property~~
* url like ...eot?#... and ...svg#... not shows
