### ISSUE TITLE
Indent inside media queries

### ISSUE THREAD

**Issue by claviska** [Cerdic/CSSTidy#39]
Hi, I'm using this fork of CSSTidy for [DirtyMarkup](http://www.dirtymarkup.com/), as the original was abandoned, doesn't support media queries, etc. So thanks for your work on this project!

Quick feature request for indenting media queries. The current output looks like this:

```css
@media (max-width: 767px) {
h1
    font-size: 2em;
}
}
```

Desired output is:

```css
@media (max-width: 767px) {
    h1
        font-size: 2em;
    }
}
```

It looks like this would require a new formatter in the template files, or maybe it could be assumed that whatever the indent level is for properties could simply be doubled.

What are your thoughts on this?
