### ISSUE TITLE
Corrupting rgb() color definition

### ISSUE THREAD

**Issue by mustafa-soner-acar** [Cerdic/CSSTidy#81]
When using " compress colors" option it does not recognize rgb() notation properly.

considering example :
```css
white10 { color: rgba(255, 255, 255, 10%); }
white20 { color: rgb(255 255 255 / 20%);   }
white30 { color: rgb(255, 255, 255, 30%);  }
```
___________________________________

Output :

Optimised color: Changed "rgb(255 255 255 / 20%)" to "red"
Optimised color: Changed "rgb(255,255,255,30%)" to "#fff"

```css
white10{color:rgba(255,255,255,10%)}
white20{color:red}
white30{color:#fff}
```
___________________________________

Should be:
```css
white10{color:#ffffff1a}
white20{color:#fff3}
white30{color:#ffffff4d}
```
